import aiomysql
import mysql_connectors

MySQLReadWriteConnector = mysql_connectors.MySQLReadWriteConnector()

'''
Creates a conversation
'''
async def create_conversation():
    pass

'''
Obtains all messages assigned to a conversation
'''
async def get_conversation(conversation_id: str):
    pass

'''
Obtains all the conversation IDs assigned to that user
'''
async def get_user_conversations(user_email: str):
    pass

'''
Adds generated by user/assistant messages assigned to a conversations
'''
async def add_message_conversation(conversation_id: str):
    pass

'''Creates model register indicating model name, origin, is_available etc'''
async def create_model(model_id: str, user_id: str, model_name: str):
    pass

